# Generated by Django 5.2.8 on 2025-11-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('max_players', models.IntegerField(default=2, verbose_name='Максимум игроков')),
                ('current_players', models.IntegerField(default=1, verbose_name='Сейчас игроков')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_game_started', models.BooleanField(default=False, verbose_name='Игра началась')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Лобби',
                'verbose_name_plural': 'Лобби',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Электронная почта')),
                ('hashed_password', models.CharField(max_length=255, verbose_name='Хешированный пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний вход')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готов')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.lobby', verbose_name='Лобби')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='lobby',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='app.user', verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=0, verbose_name='Текущий ход')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Игра закончена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.lobby', verbose_name='Лобби')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='app.user', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
    ]
