# Generated by Django 5.2.8 on 2025-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='lobby',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Готов к игре'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
