# Generated by Django 5.2.8 on 2025-11-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_player_options_alter_lobby_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='is_game_started',
            field=models.BooleanField(default=False, verbose_name='Игра в процессе'),
        ),
    ]
