# Generated by Django 5.2.8 on 2025-11-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.lobby', verbose_name='Лобби'),
        ),
    ]
