# Generated by Django 5.2.8 on 2025-11-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_player_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='app.lobby', verbose_name='Лобби'),
        ),
    ]
